#!/usr/bin/env node
// Tavern League TCG - card pool builder.
//
// Reads the cached datasets (tools/cache/era_data.json + tbc_data.json,
// fetched by fetch_dataset.js) and emits TavernLeagueTCG/CardPool.lua.
// Pure transform: rerunning is instant, so pool rules can be iterated
// without re-downloading.
//
//   node tools/build_cardpool.js
//
// Also writes tools/report_included.csv and tools/report_excluded.csv for
// eyeballing the junk filter.

'use strict';

const fs = require('fs');
const path = require('path');

const CACHE = path.join(__dirname, 'cache');
const OUT_LUA = path.join(__dirname, '..', 'TavernLeagueTCG', 'CardPool.lua');
const OVERRIDES = path.join(__dirname, 'overrides.csv');

// item classes to include as cards (matched against the dataset's `class`)
const INCLUDE_CLASSES = new Set(['Weapon', 'Armor', 'Trade Goods']);

// Junk/internal items: any match excludes the item.
const JUNK_PATTERNS = [
  /deprecated/i,
  /^monster ?-/i,
  /^test\b/i,
  /\(test\)/i,
  /^qa\b/i,
  /\[ph\]/i,
  /\[dnt\]/i,
  /\bdo not use\b/i,
  /\bunused\b/i,
  /^zz/i,
  /^old\b/i,
  /\(old\)/i,
  /\bplaceholder\b/i,
  /^\d+ (green|blue|epic|test)\b/i,
  /^delete me/i,
  /^broken\b/i,
  /^dnd\b/i,
  /^gm only/i,
  /^game master/i,
  /^level \d+ test/i,
];

const QUALITY_TIER = {
  Poor: 1, Common: 1, Uncommon: 2, Rare: 3, Epic: 4, Legendary: 5, Artifact: 5, Heirloom: 5,
};

// ---------------------------------------------------------------------------

function loadItems(file) {
  const p = path.join(CACHE, file);
  if (!fs.existsSync(p)) {
    console.error(`missing ${p} - run: node tools/fetch_dataset.js`);
    process.exit(1);
  }
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

function loadOverrides() {
  const map = new Map();
  if (!fs.existsSync(OVERRIDES)) return map;
  for (const line of fs.readFileSync(OVERRIDES, 'utf8').split(/\r?\n/)) {
    const t = line.split('#')[0].trim();
    if (!t || t.toLowerCase().startsWith('itemid')) continue;
    const [id, action, tier] = t.split(',').map((s) => s.trim());
    map.set(parseInt(id, 10), {
      action: (action || '').toLowerCase(),
      tier: tier ? parseInt(tier, 10) : null,
    });
  }
  return map;
}

const isJunk = (name) => JUNK_PATTERNS.some((re) => re.test(name));
const csvName = (name) => '"' + name.replace(/"/g, "'") + '"';

function main() {
  const era = loadItems('era_data.json');
  const tbc = loadItems('tbc_data.json');
  const overrides = loadOverrides();

  const eraIds = new Set(era.map((i) => i.itemId));
  // prefer the era record for era items (era-accurate quality/class);
  // TBC-only items come from the TBC dataset
  const byId = new Map();
  for (const item of tbc) byId.set(item.itemId, item);
  for (const item of era) byId.set(item.itemId, item);

  console.log(`datasets: ${era.length} era items, ${tbc.length} tbc-era items, ` +
    `${byId.size} combined, ${overrides.size} overrides`);

  const rows = [];
  const included = [];
  const excluded = [];

  for (const id of [...byId.keys()].sort((a, b) => a - b)) {
    const item = byId.get(id);
    const isTbcOnly = !eraIds.has(id);
    const ov = overrides.get(id);

    let reason = null;
    if (ov && ov.action === 'exclude') reason = 'override';
    else if (!INCLUDE_CLASSES.has(item.class)) reason = `class ${item.class}`;
    else if (!item.name || isJunk(item.name)) reason = 'junk name';

    if (reason) {
      excluded.push(`${id},${csvName(item.name || '?')},${item.class},${item.quality},${reason}`);
      continue;
    }

    let tier = QUALITY_TIER[item.quality] || 1;
    if (ov && ov.tier && (ov.action === 'tier' || ov.action === 'promote' || ov.action === 'demote')) {
      tier = Math.min(5, Math.max(1, ov.tier));
    }

    rows.push({ i: id, r: tier, x: isTbcOnly ? 1 : 0, n: item.name });
    included.push(`${id},${csvName(item.name)},${item.class},${item.quality},${tier},${isTbcOnly ? 1 : 0}`);
  }

  const byRarity = {};
  const byRarityTbc = {};
  let tbcCount = 0;
  for (const r of rows) {
    byRarity[r.r] = (byRarity[r.r] || 0) + 1;
    if (r.x) {
      tbcCount++;
      byRarityTbc[r.r] = (byRarityTbc[r.r] || 0) + 1;
    }
  }
  console.log(`pool: ${rows.length} cards (${tbcCount} TBC-gated), excluded ${excluded.length}`);
  console.log('rarity spread (all):', byRarity);
  console.log('rarity spread (tbc-only):', byRarityTbc);

  const lines = [];
  lines.push('-- Tavern League TCG card pool. GENERATED by tools/build_cardpool.js -');
  lines.push('-- do not edit by hand. Regenerate:');
  lines.push('--   node tools/fetch_dataset.js && node tools/build_cardpool.js');
  lines.push('--');
  lines.push(`-- ${rows.length} cards (${tbcCount} TBC-gated). i = itemId, r = rarity tier 1-5,`);
  lines.push('-- n = name (bundled so the binder never waits on the item cache),');
  lines.push('-- x = 1 marks TBC-only items (skipped on Classic Era clients).');
  lines.push('');
  lines.push('local ADDON, TT = ...');
  lines.push('');
  lines.push('TT.pool = {');
  const luaName = (s) => '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
  for (const r of rows) {
    lines.push(`{i=${r.i},r=${r.r},n=${luaName(r.n)}${r.x ? ',x=1' : ''}},`);
  }
  lines.push('}');
  lines.push('');
  fs.writeFileSync(OUT_LUA, lines.join('\n'));
  console.log(`wrote ${OUT_LUA}`);

  fs.writeFileSync(path.join(__dirname, 'report_included.csv'),
    'itemId,name,class,quality,tier,tbcOnly\n' + included.join('\n'));
  fs.writeFileSync(path.join(__dirname, 'report_excluded.csv'),
    'itemId,name,class,quality,reason\n' + excluded.join('\n'));
  console.log('wrote report_included.csv / report_excluded.csv');
}

main();
